tests

diff --git a/.github/workflows/android_app_build_debug.yml b/.github/workflows/android_app_build_debug.yml
--- a/.github/workflows/android_app_build_debug.yml
+++ b/.github/workflows/android_app_build_debug.yml
@@ -7,7 +7,7 @@ on:
   workflow_dispatch:
 
 concurrency:
-  group: ${{ github.workflow }}-${{ github.branch }}
+  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
   cancel-in-progress: true
 
 jobs:
@@ -70,6 +70,7 @@ jobs:
         if: steps.avd-cache.outputs.cache-hit != 'true'
         uses: reactivecircus/android-emulator-runner@v2
         with:
+          avd-name: "avd-test"
           api-level: 29
           force-avd-creation: false
           emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
@@ -79,12 +80,25 @@ jobs:
       - name: Check GithubA env
         run: echo "$GITHUB_CONTEXT"
 
+      - name: tests
+        run: |
+          if ! "$ANDROID_SDK_TOOLS_PATH"/avdmanager list avd | grep -q "Name: avd-test"; then
+            echo "Error: AVD named avd-test not found."
+            exit 1
+          fi
+          "$ANDROID_SDK_TOOLS_PATH"/emulator -avd "avd-test"
+
+      - name: tests 2
+        run: |
+          chmod +x .github/workflows/scripts/setup_emulators.sh
+          ./.github/workflows/scripts/setup_emulators.sh
+
       - name: Start Android Emulator
-        timeout-minutes: 10
+        timeout-minutes: 1
         continue-on-error: true
         run: |
           echo "Starting emulator"
-          nohup $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-snapshot -no-window &
+          nohup $ANDROID_HOME/emulator/emulator -avd "avd-test" -no-audio -no-snapshot -no-window &
           $ANDROID_HOME/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\r') ]]; do sleep 1; done; input keyevent 82'
           $ANDROID_HOME/platform-tools/adb devices
           echo "Emulator started"
